### ISSUE TITLE
Feilmelding under oppsett av miljø

### ISSUE THREAD

**Issue by teodorlu** [hybrida/hybridjango#3]
Hei,

**Jeg gjør:**
1. Setter opp `venv`
2. Kjører

    ```
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
    ```
    
**Jeg forventer at skjer:**

Siden kjører lokalt

**Dette skjer:**

Feilmelding:

```
python manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x7fe57a2726e0>
Traceback (most recent call last):
  File "/home/teodorlu/git/hybridjango/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/teodorlu/git/hybridjango/venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/teodorlu/git/hybridjango/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/teodorlu/git/hybridjango/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/teodorlu/git/hybridjango/venv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/teodorlu/git/hybridjango/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/teodorlu/git/hybridjango/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/teodorlu/git/hybridjango/apps/kiltshop/models.py", line 2, in <module>
    from apps.registration.models import Hybrid
ImportError: No module named registration.models
```

**Comment by simennj** [comment]
Klarte kun å reprodusere det i python 2, skal ta det opp neste møte men python 3 kan brukes i mellomtiden.

**Comment by teodorlu** [comment]
Stemmer at jeg kjørte Python 2. Om dere gjør at Python 2 kan brukes eller
spesifiserer at Python 3 skal brukes i README er hipp som happ for meg.

**Comment by teodorlu** [comment]
Prøvde med Python 3. Ser ut som den prøver å skrive filer til systemmapper og ikke lokalt venv.

Hvilket OS kjører du? Har du installert Python fra pakkebehandler eller selv?

```
$ sudo apt install python3 python3-pip
# ...
$ source venv/bin/activate
$ pip3 install --upgrade pip
# ...
$ pip3 install -r requirements.txt
Collecting Django (from -r requirements.txt (line 1))
  Using cached Django-1.10.5-py2.py3-none-any.whl
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2))
Collecting pytz (from -r requirements.txt (line 3))
  Using cached pytz-2016.10-py2.py3-none-any.whl
Collecting django-widget-tweaks (from -r requirements.txt (line 4))
  Using cached django_widget_tweaks-1.4.1-py2.py3-none-any.whl
Installing collected packages: Django, pytz, django-widget-tweaks
Exception:
Traceback (most recent call last):
  File "/home/teodorlu/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/teodorlu/.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/teodorlu/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/teodorlu/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/teodorlu/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/teodorlu/.local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/teodorlu/.local/lib/python3.5/site-packages/pip/wheel.py", line 287, in clobber
    ensure_dir(dest)  # common for the 'include' path
  File "/home/teodorlu/.local/lib/python3.5/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.5/site-packages'
```

**Comment by simennj** [comment]
Virker som om det er systeminstallasjonen av pip3 som blir brukt, du må lage et nytt venv basert på python3 og bruke pip der (siden det ikke er noen pip3 i et python2 venv så ble systeminstallasjonen av pip3 kalt).
`virtualenv venv --python=python3`
`source venv/bin/activate`
`pip install -U pip`
`pip install -r requirements.txt`

**Comment by teodorlu** [comment]
`rm -rf venv`, fulgte Simens instruksjoner, og woila. Takk!
